### PR TITLE
Made first pull request

### PR DESCRIPTION
**Pull request by Gbowker**
# testy
`

> test of how to pull request with review.

`

### CODE REVIEW

**Review by Sakina-1 — APPROVED** [review]
Proud of you

**Comment by Gbowker** [comment]
Thanks <3
Way I did this:
create/upload file ---> create in new branch ---> add all the comments etc. ---> **draft pull request** to have someone review it before it gets put on/**pull request** to just put it on with no review needed.

**Comment by Gbowker** [comment]
Now how to merge it...?

**Comment by Gbowker** [comment]
Ah ok, so submitter must click 'ready for approval' aswell, then you can merge the branch onto master!

**Comment by Sakina-1** [comment]
Oh okay. Yeah because merging is blocked in draft requests. Just Googled this:

_Change the status to “Ready for review” near the bottom of your pull request to remove the draft state and allow merging according to your project's settings._

**Comment by Sakina-1** [comment]
Oh you've already done it XD

**Comment by Gbowker** [comment]
Now I have three options to merge: (this one doesn't clash with master, but if it did these options would be more different in their effect.)
**merge commit**: all the commits here will be added, head changed to master:
A---B---C---D---M  master
    (AtoE, GtoM)
      E---F---G    develop

**squash and merge**: gets changes from this branch into master but doesn't move head and leaves this branch detached from master:
A---B---C---D---M  master
     (AtoE, M with all changes in G)          
      E---F---G    this branch

**rebase and merge**: tail end of this branch onto master and moves head to end of this branch:
A -- B -- C -- D (master)
+
E -- F -- G (this branch)
 (master plus this branch)    --- >               A -- B -- C -- D -- E -- F -- G(head)
This according to:

merge commit & squash merge:
https://stackoverflow.com/questions/47089913/merge-commit-without-squash-vs-with-squash-option

rebase and merge:
https://medium.com/datadriveninvestor/git-rebase-vs-merge-cc5199edd77c

**Comment by Gbowker** [comment]
Hope all this helps, use this as a guide!

**Comment by Gbowker** [comment]
Also going to keep this branch so that these comments remain as a guide

**Pull request merged**
